name: Build Check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      # Eslint check
      - run: npm run lint

      # Test
      - run: npm run test

      - run: npm run build
